# -*- coding: utf-8 -*-
"""Генератор синтетического датасета для тестов.

Реальные цеховые файлы в репозиторий не выкладываются, поэтому тесты
работают на синтетике. Датасет описан явно в SHIFT и EDGE_CASES: эталонные
суммы считаются из этого описания, а не из разбора сгенерированных файлов,
поэтому тест проверяет парсер независимым путём.

Воспроизводит структурные особенности формата NCeXpress FMS, на которых
ломается наивный разбор:

  * одна деталь может лежать в нескольких блоках PART_DATA одного файла;
  * SHEET_COUNT встречается в файле дважды, второй раз — в строке
    IF (SHEET_COUNT > R400) ... , которую нельзя принимать за объявление;
  * блоки с PART_NAME="SCRAP" — обрезки, в учёт не идут;
  * .nc пишется с LF, .fms — с CRLF;
  * файлы бывают в разных однобайтовых кодировках.

Запуск:  python3 tools/make_fixtures.py
"""

import json
import os
import shutil

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
FIXTURES = os.path.join(ROOT, 'tests', 'fixtures')

BANNER = '; SYNTHETIC TEST DATA - generated by tools/make_fixtures.py'

# Габариты деталей: имя -> (X, Y). Нужны для .fms, на учёт не влияют.
PART_DIMS = {
    'PART_NO01': (660.0, 60.0),
    'PART_NO02': (165.0, 95.0),
    'PART_NO03': (210.0, 410.0),
    'PART_NO04': (840.0, 60.0),
    'PART_NO05': (390.0, 410.0),
    'PART_NO06': (750.0, 130.0),
    'PART_NO07': (120.0, 120.0),
    'PART_NO08': (480.0, 220.0),
    'PART_NO09': (95.0, 95.0),
    'PART_NO10': (300.0, 180.0),
    'PART_NO11': (1200.0, 90.0),
    'PART_NO12': (250.0, 250.0),
    'PART_NO13': (140.0, 70.0),
    'PART_NO14': (520.0, 310.0),
}

TOOLS = ['TOOL_NA01', 'TOOL_NA11', 'TOOL_NA20', 'TOOL_NA22', 'TOOL_NA31']

# Габариты листа. В реальном задании их бывает несколько, поэтому в наборе
# тоже больше одного — иначе колонка размера ничего не проверяет.
DEFAULT_SHEET = (2500, 1250)
SHEET_OVERRIDES = {6: (3000, 1500), 10: (600, 415)}

# Имена в стиле реального производства: ДДММГГ + код участка + номер.
# Набор подобран так, чтобы ловить ровно те ловушки, которых нет в PRG_01..12:
#   * число в конце имени не возрастает — после ...202004 идёт ...201001;
#   * три имени дают одинаковый хвост 201001, потому что даты разные.
# Порядок выполнения при этом задаётся естественной сортировкой имени.
REALISTIC_NAMES = {
    1: '000101zz201001',
    2: '000101zz201002',
    3: '000101zz201003',
    4: '000101zz201005',
    5: '000101zz201006',
    6: '000101zz202003',
    7: '000101zz202004',
    8: '000102zz201001',
    9: '000102zz203001',
    10: '000102zz204001',
    11: '000103zz201001',
    12: '000103zz202001',
}

# Программы, у которых карты наладки нет. В реальном задании PDF есть не
# у всех, и утилита обязана переживать это без ошибки.
WITHOUT_DOCUMENT = {4, 9}


def sheet_size(prg_no):
    return SHEET_OVERRIDES.get(prg_no, DEFAULT_SHEET)


def pdf_bytes(title):
    """Минимальная корректная одностраничная PDF-заглушка.

    Настоящие карты наладки в репозиторий не выкладываются, но утилита должна
    находить файл рядом с программой и отдавать его системе.
    """
    body = 'BT /F1 18 Tf 72 760 Td ({}) Tj ET'.format(title).encode('ascii')
    objects = [
        b'<</Type/Catalog/Pages 2 0 R>>',
        b'<</Type/Pages/Kids[3 0 R]/Count 1>>',
        b'<</Type/Page/Parent 2 0 R/MediaBox[0 0 595 842]'
        b'/Resources<</Font<</F1 4 0 R>>>>/Contents 5 0 R>>',
        b'<</Type/Font/Subtype/Type1/BaseFont/Helvetica>>',
        b'<</Length ' + str(len(body)).encode('ascii') + b'>>stream\n'
        + body + b'\nendstream',
    ]
    out = bytearray(b'%PDF-1.4\n')
    offsets = []
    for index, obj in enumerate(objects, start=1):
        offsets.append(len(out))
        out += str(index).encode('ascii') + b' 0 obj' + obj + b'endobj\n'
    xref_at = len(out)
    out += b'xref\n0 ' + str(len(objects) + 1).encode('ascii') + b'\n'
    out += b'0000000000 65535 f \n'
    for offset in offsets:
        out += ('%010d 00000 n \n' % offset).encode('ascii')
    out += (b'trailer<</Size ' + str(len(objects) + 1).encode('ascii')
            + b'/Root 1 0 R>>\nstartxref\n'
            + str(xref_at).encode('ascii') + b'\n%%EOF\n')
    return bytes(out)

# Сменное задание.
#   номер УП -> (число листов, [(деталь, штук в блоке), ...], число обрезков)
# Список блоков намеренно содержит повторы одной детали — так пишет CAM,
# когда одинаковые детали разнесены по листу разными группами.
SHIFT = {
    1:  (1, [('PART_NO01', 2), ('PART_NO02', 4), ('PART_NO05', 1),
             ('PART_NO13', 3), ('PART_NO14', 2)], 3),
    2:  (1, [('PART_NO03', 2), ('PART_NO05', 2), ('PART_NO07', 6),
             ('PART_NO14', 1)], 2),
    3:  (2, [('PART_NO02', 3), ('PART_NO02', 1), ('PART_NO09', 2)], 4),
    4:  (1, [('PART_NO04', 5), ('PART_NO10', 1)], 1),
    5:  (1, [('PART_NO05', 3), ('PART_NO05', 1), ('PART_NO05', 1)], 2),
    6:  (3, [('PART_NO06', 1), ('PART_NO11', 2)], 2),
    7:  (1, [('PART_NO01', 4), ('PART_NO08', 2), ('PART_NO12', 3)], 5),
    8:  (1, [('PART_NO07', 2), ('PART_NO09', 4)], 2),
    9:  (2, [('PART_NO10', 2), ('PART_NO10', 2), ('PART_NO03', 1)], 3),
    10: (1, [('PART_NO12', 1), ('PART_NO06', 2)], 1),
    11: (1, [('PART_NO08', 3), ('PART_NO11', 1)], 2),
    12: (1, [('PART_NO05', 4), ('PART_NO04', 2), ('PART_NO02', 2)], 3),
}


def expected_balance(shift):
    """Эталонный свод смены, посчитанный прямо из описания задания."""
    totals = {}
    last_prg = {}
    per_program = {}
    for prg in sorted(shift):
        sheets, blocks, _ = shift[prg]
        in_this = {}
        for name, qty in blocks:
            in_this[name] = in_this.get(name, 0) + qty
        per_program[prg] = {n: q * sheets for n, q in sorted(in_this.items())}
        for name, qty in in_this.items():
            totals[name] = totals.get(name, 0) + qty * sheets
            last_prg[name] = prg
    parts = []
    for name in sorted(totals):
        parts.append({
            'part': name,
            'total': totals[name],
            'last_position': last_prg[name],
            'last_program': 'PRG_{:02d}'.format(last_prg[name]),
        })
    return {
        'realistic_names': {str(k): v for k, v in sorted(REALISTIC_NAMES.items())},
        'sheet_sizes': {str(k): list(sheet_size(k)) for k in sorted(shift)},
        'without_document': sorted(WITHOUT_DOCUMENT),
        'programs': len(shift),
        'unique_parts': len(totals),
        'total_pieces': sum(totals.values()),
        'parts': parts,
        'per_program': {str(k): v for k, v in per_program.items()},
    }


def nc_text(prg_no, sheets, blocks, scrap, name_fmt='PRG_{:02d}', comment=None):
    """Управляющая программа в формате NCeXpress FMS."""
    prg = name_fmt.format(prg_no)
    size_x, size_y = sheet_size(prg_no)
    out = [
        '%_N_{}_MPF'.format(prg),
        ';$PATH=/_N_WKS_DIR/_N_WORK_1_WPD',
        '; {}'.format(prg),
        '; NCeXpress FMS',
        BANNER,
    ]
    if comment:
        out.append('; {}'.format(comment))
    out += [
        '; *** DATE : 5/15/2024 ***',
        '; *** TIME : 10:00:00 ***',
        'MATERIAL="Steel"',
        'THICKNESS=2',
        'SCRAP_BOX=1',
        'X_DIM={}'.format(size_x),
        'Y_DIM={}'.format(size_y),
        'CLAMP_1=75.250',
        'CLAMP_2=1035.099',
        'CLAMP_3=1994.948',
        'STROKE_LENGTH=90',
        'ACCELERATION=91',
        'RAM_SPEED=100',
        'SHEET_COUNT={}'.format(sheets),
        'FIRST_X=58.20',
        'FIRST_Y=200.00',
        'FIRST_TOOL=9',
        ';(AUTOMATIC LOADING)',
        'PIN_NO=1',
        'TABLE_NO=1',
        'STORAGE_ADDRESS=0',
        'X_CARR_POS=275',
        ';#RS_CONFIG',
        'RS_STROKE_LENGTH=29',
        'BLADE_CLEARANCE=0.16',
        'SHEAR_SPEED(50,50)',
        ' ',
    ]

    idx = 0
    # Обрезки идут первыми, как в реальных программах.
    for i in range(scrap):
        idx += 1
        out += [
            'PART_DATA={}'.format(idx),
            'PART_NAME="SCRAP"',
            'PART_ID=0',
            'QUANTITY=1',
            'PART_X_DIM=40',
            'PART_Y_DIM={:.2f}'.format(100.0 + i * 37.5),
            'ANGLE=0',
            'ADDRESS=1',
            'SAVE_DATA',
            ' ',
        ]
    for pos, (name, qty) in enumerate(blocks):
        idx += 1
        dx, dy = PART_DIMS[name]
        out += [
            'PART_DATA={}'.format(idx),
            'PART_NAME="{}"'.format(name),
            'PART_ID={}'.format(int(name[-2:])),
            'QUANTITY={}'.format(qty),
            'PART_X_DIM={}'.format(dx),
            'PART_Y_DIM={}'.format(dy),
            'ANGLE={}'.format(0 if pos % 2 == 0 else 270),
            'ADDRESS={}'.format(10 + pos),
            'SAVE_DATA',
            ' ',
        ]

    for i, tool in enumerate(TOOLS, start=1):
        out += [
            '; TOOL_CHANGE,ID+{0}+{0}'.format(tool),
            'N{} TOOL({},500.000,200.000,{})'.format(i, i, i),
            'X500.000Y200.000',
            'X500.000Y300.000M25',
        ]
    out += [
        'N1013 RS_END(1)',
        'N2022 LAST_PART(28,2500)',
        'N31 UNLOAD(1)',
        # Второе вхождение SHEET_COUNT: не объявление, а условие перехода.
        'IF (SHEET_COUNT > R400) AND ($A_IN[16]==1) GOTOB MAIN',
        'END(1)',
        'M30',
    ]
    return '\n'.join(out) + '\n'


def fms_text(prg_no, sheets, blocks, name_fmt='PRG_{:02d}'):
    """Отчёт наладки: #RSCUT — агрегат по детали, #COMPONENTS — по блокам."""
    prg = name_fmt.format(prg_no)
    size_x, size_y = sheet_size(prg_no)
    agg = {}
    for name, qty in blocks:
        agg[name] = agg.get(name, 0) + qty

    out = [
        ';',
        ';NCeXpress FMS report file',
        ';',
        BANNER,
        '#GENERAL',
        'DATE :  Wednesday, May 15, 10 : 00 : 00, 2024',
        'UNITS : MM',
        'PRG.NAME : {}'.format(prg),
        'PRG.NO : NOT USED',
        'NESTING NAME : {}'.format(prg),
        'NC FILE NAME : C:\\CAM\\PROGRAMS\\{}.NC'.format(prg),
        'MACHINE : MACHINE_A (pp POSTPROC.dll)',
        'JOB ID : {}'.format(prg),
        'MATERIAL : Steel',
        'THICKNESS : 2',
        'SHEET SIZE X : {}'.format(size_x),
        'SHEET SIZE Y : {}'.format(size_y),
        'PLATE NAME :PLATE_A',
        'NUMBER OF SHEETS : {}'.format(sheets),
        'NUMBER OF CLAMPS : 3',
        '#RSCUT',
    ]
    for name in sorted(agg):
        dx, dy = PART_DIMS[name]
        out.append('{} : Size {} x {}, Number={}, Forming=0'.format(
            name, dx, dy, agg[name]))
        out.append('C:\\CAM\\PARTS\\{}.cp'.format(name))

    out += [
        '#TIMES',
        'SHEET USAGE EFFICIENCY : 75.0%',
        'TOOL CHANGES : {}'.format(len(TOOLS)),
        'TOTAL TIME per SHEET : 5min, 00sec',
        '#TOOLS',
        'NUMBER OF TOOLS : {}'.format(len(TOOLS)),
    ]
    for i, tool in enumerate(TOOLS, start=2):
        out.append('R:X20Y10:0:0.4::{}:;{};'.format(i, tool))

    out.append('#COMPONENTS')
    for pos, (name, qty) in enumerate(blocks):
        dx, dy = PART_DIMS[name]
        # Пробелы вокруг "=" здесь не такие, как в #RSCUT. Так в оригинале.
        out.append('({}) {} : Size {} x {}, Number = {}, Rev ='.format(
            pos, name, dx, dy, qty))
        out.append('({}) PATH : C:\\CAM\\PARTS\\{}.cp'.format(pos, name))
    return '\r\n'.join(out) + '\r\n'


# Краевые случаи: имя файла -> (описание, текст, кодировка)
def edge_cases():
    base_sheets, base_blocks, base_scrap = 1, [('PART_NO01', 2)], 1
    ok = nc_text(1, base_sheets, base_blocks, base_scrap)
    return {
        'empty.nc': (
            'Пустой файл', '', 'utf-8'),
        'no_sheet_count.nc': (
            'Нет объявления SHEET_COUNT, но есть IF со SHEET_COUNT',
            ok.replace('SHEET_COUNT=1\n', ''), 'utf-8'),
        'only_scrap.nc': (
            'Только обрезки, деталей нет',
            nc_text(1, 1, [], 4), 'utf-8'),
        'no_quantity.nc': (
            'Блок PART_DATA без QUANTITY',
            ok.replace('QUANTITY=2\n', ''), 'utf-8'),
        'zero_sheets.nc': (
            'SHEET_COUNT=0 — программа в задание не пошла',
            nc_text(1, 0, base_blocks, base_scrap), 'utf-8'),
        'cp1251.nc': (
            'Кириллица в комментарии, кодировка windows-1251',
            nc_text(1, 1, base_blocks, base_scrap,
                    comment='Наладка выполнена, лист 2 мм'), 'cp1251'),
        'cp866.nc': (
            'Кириллица в комментарии, кодировка cp866',
            nc_text(1, 1, base_blocks, base_scrap,
                    comment='Проверить прижимы перед пуском'), 'cp866'),
        'crlf.nc': (
            'Те же данные, но перенос строк CRLF',
            ok.replace('\n', '\r\n'), 'utf-8'),
    }


def write(path, text, encoding='utf-8', newline=''):
    with open(path, 'w', encoding=encoding, newline=newline) as fh:
        fh.write(text)


def main():
    if os.path.isdir(FIXTURES):
        shutil.rmtree(FIXTURES)

    # 1. Нормальная смена: PRG_01..PRG_12, .nc + .fms
    shift_dir = os.path.join(FIXTURES, 'shift_ok')
    os.makedirs(shift_dir)
    for prg in sorted(SHIFT):
        sheets, blocks, scrap = SHIFT[prg]
        write(os.path.join(shift_dir, 'PRG_{:02d}.nc'.format(prg)),
              nc_text(prg, sheets, blocks, scrap))
        write(os.path.join(shift_dir, 'PRG_{:02d}.fms'.format(prg)),
              fms_text(prg, sheets, blocks))
        if prg not in WITHOUT_DOCUMENT:
            with open(os.path.join(shift_dir, 'PRG_{:02d}.pdf'.format(prg)),
                      'wb') as fh:
                fh.write(pdf_bytes('SYNTHETIC SETUP REPORT PRG_{:02d}'.format(prg)))

    # 2. Та же смена без ведущих нулей: PRG_1..PRG_12.
    #    Ловушка на сортировку: по алфавиту PRG_10 встаёт раньше PRG_9,
    #    и крайняя программа для детали определяется неверно.
    unpadded_dir = os.path.join(FIXTURES, 'unpadded')
    os.makedirs(unpadded_dir)
    for prg in sorted(SHIFT):
        sheets, blocks, scrap = SHIFT[prg]
        write(os.path.join(unpadded_dir, 'PRG_{}.nc'.format(prg)),
              nc_text(prg, sheets, blocks, scrap, name_fmt='PRG_{}'))
        write(os.path.join(unpadded_dir, 'PRG_{}.fms'.format(prg)),
              fms_text(prg, sheets, blocks, name_fmt='PRG_{}'))

    # 3. Имена реального вида: ловушка на порядок выполнения
    realistic_dir = os.path.join(FIXTURES, 'realistic')
    os.makedirs(realistic_dir)
    for prg in sorted(SHIFT):
        sheets, blocks, scrap = SHIFT[prg]
        stem = REALISTIC_NAMES[prg]
        write(os.path.join(realistic_dir, stem + '.nc'),
              nc_text(prg, sheets, blocks, scrap, name_fmt='{}'.format(stem)))
        write(os.path.join(realistic_dir, stem + '.fms'),
              fms_text(prg, sheets, blocks, name_fmt='{}'.format(stem)))

    # 4. Краевые случаи
    edge_dir = os.path.join(FIXTURES, 'edge')
    os.makedirs(edge_dir)
    notes = {}
    for fname, (descr, text, enc) in sorted(edge_cases().items()):
        write(os.path.join(edge_dir, fname), text, encoding=enc)
        notes[fname] = {'description': descr, 'encoding': enc}
    write(os.path.join(edge_dir, 'README.json'),
          json.dumps(notes, ensure_ascii=False, indent=2, sort_keys=True) + '\n')

    # 5. Эталонный свод
    expected = expected_balance(SHIFT)
    write(os.path.join(FIXTURES, 'expected.json'),
          json.dumps(expected, ensure_ascii=False, indent=2, sort_keys=True) + '\n')

    print('Смена:          {} программ, {} позиций, {} деталей'.format(
        expected['programs'], expected['unique_parts'], expected['total_pieces']))
    print('shift_ok:       {} файлов'.format(len(os.listdir(shift_dir))))
    print('unpadded:       {} файлов'.format(len(os.listdir(unpadded_dir))))
    print('realistic:      {} файлов'.format(len(os.listdir(realistic_dir))))
    print('edge:           {} файлов'.format(len(os.listdir(edge_dir))))
    print('эталон:         tests/fixtures/expected.json')


if __name__ == '__main__':
    main()
